import type {
  Accession,
  Bench,
  BenchReservation,
  ClearanceSnapshot,
  Flag,
  ObservationPass,
  Trial,
  WorkspaceState,
} from "../domain/types";

const trials: Trial[] = [
  {
    id: "trial-sol-01",
    code: "SOL-01",
    cropFamily: "茄科",
    objective: "比较紧凑型番茄品种在温室内的早期坐果表现。",
    season: "春季",
    startDate: "2026-02-16",
    endDate: "2026-05-18",
    state: "active",
  },
  {
    id: "trial-ama-02",
    code: "AMA-02",
    cropFamily: "苋科",
    objective: "在限水条件下评估三个甜菜批次的叶片品质。",
    season: "夏季",
    startDate: "2026-04-01",
    endDate: "2026-07-12",
    state: "active",
  },
  {
    id: "trial-bra-03",
    code: "BRA-03",
    cropFamily: "十字花科",
    objective: "筛选羽衣甘蓝品系的早期茎秆强度和叶片一致性。",
    season: "秋季",
    startDate: "2026-07-20",
    endDate: "2026-10-08",
    state: "draft",
  },
];

const accessions: Accession[] = [
  {
    id: "acc-tom-01",
    trialId: "trial-sol-01",
    accessionNo: "ACC-0001",
    cultivar: "Tiny Tim",
    source: "Pioneer Seed Lab",
    propagatedOn: "2026-02-18",
    quantity: 96,
    trayCells: 104,
    preferredLight: "full-sun",
    genotypeNote: "有限生长型矮化品系，节间紧凑。",
    labels: ["矮化", "早熟"],
  },
  {
    id: "acc-tom-02",
    trialId: "trial-sol-01",
    accessionNo: "ACC-0002",
    cultivar: "Micro Tom",
    source: "Pioneer Seed Lab",
    propagatedOn: "2026-02-18",
    quantity: 96,
    trayCells: 104,
    preferredLight: "full-sun",
    genotypeNote: "矮化品种，单盆果实密度较高。",
    labels: ["矮化", "果实"],
  },
  {
    id: "acc-tom-03",
    trialId: "trial-sol-01",
    accessionNo: "ACC-0003",
    cultivar: "Yellow Pear",
    source: "Regional Germplasm Bank",
    propagatedOn: "2026-02-20",
    quantity: 72,
    trayCells: 128,
    preferredLight: "full-sun",
    genotypeNote: "无限生长型樱桃番茄品系，用于活力比较。",
    labels: ["樱桃", "活力"],
  },
  {
    id: "acc-bee-01",
    trialId: "trial-ama-02",
    accessionNo: "ACC-0004",
    cultivar: "Bull's Blood",
    source: "Root Heritage",
    propagatedOn: "2026-04-01",
    quantity: 120,
    trayCells: 128,
    preferredLight: "partial-shade",
    genotypeNote: "深红叶用批次，中等耐热性。",
    labels: ["叶用", "颜色"],
  },
  {
    id: "acc-bee-02",
    trialId: "trial-ama-02",
    accessionNo: "ACC-0005",
    cultivar: "Golden Detroit",
    source: "Root Heritage",
    propagatedOn: "2026-04-01",
    quantity: 120,
    trayCells: 128,
    preferredLight: "partial-shade",
    genotypeNote: "金色甜菜品系，用于低草酸筛选。",
    labels: ["金色", "低草酸"],
  },
  {
    id: "acc-bee-03",
    trialId: "trial-ama-02",
    accessionNo: "ACC-0006",
    cultivar: "Chioggia",
    source: "Root Heritage",
    propagatedOn: "2026-04-02",
    quantity: 90,
    trayCells: 72,
    preferredLight: "partial-shade",
    genotypeNote: "条纹甜菜，用于质地和储藏性检查。",
    labels: ["条纹", "储藏"],
  },
  {
    id: "acc-kale-01",
    trialId: "trial-bra-03",
    accessionNo: "ACC-0007",
    cultivar: "Lacinato",
    source: "Brassica Works",
    propagatedOn: "2026-07-20",
    quantity: 80,
    trayCells: 72,
    preferredLight: "partial-shade",
    genotypeNote: "传统羽衣甘蓝品系，叶片深色且有褶皱。",
    labels: ["传统", "叶用"],
  },
  {
    id: "acc-kale-02",
    trialId: "trial-bra-03",
    accessionNo: "ACC-0008",
    cultivar: "Winterbor",
    source: "Brassica Works",
    propagatedOn: "2026-07-20",
    quantity: 80,
    trayCells: 72,
    preferredLight: "partial-shade",
    genotypeNote: "卷叶羽衣甘蓝杂交种，耐寒性较好。",
    labels: ["杂交", "耐寒"],
  },
];

const benches: Bench[] = [
  {
    id: "bench-east-1",
    code: "E-1",
    sector: "东翼",
    capacity: 4,
    assignedIds: ["acc-tom-01", "acc-tom-02"],
    lightProfile: "full-sun",
    irrigationLine: "IR-1",
    status: "assigned",
  },
  {
    id: "bench-east-2",
    code: "E-2",
    sector: "东翼",
    capacity: 4,
    assignedIds: [],
    lightProfile: "full-sun",
    irrigationLine: "IR-1",
    status: "available",
  },
  {
    id: "bench-west-1",
    code: "W-1",
    sector: "西翼",
    capacity: 5,
    assignedIds: ["acc-bee-01", "acc-bee-02"],
    lightProfile: "partial-shade",
    irrigationLine: "IR-2",
    status: "assigned",
  },
  {
    id: "bench-west-2",
    code: "W-2",
    sector: "西翼",
    capacity: 5,
    assignedIds: ["acc-bee-03"],
    lightProfile: "partial-shade",
    irrigationLine: "IR-2",
    status: "assigned",
  },
  {
    id: "bench-north-1",
    code: "N-1",
    sector: "北翼",
    capacity: 4,
    assignedIds: [],
    lightProfile: "shade",
    irrigationLine: "IR-3",
    status: "available",
  },
  {
    id: "bench-north-2",
    code: "N-2",
    sector: "北翼",
    capacity: 4,
    assignedIds: [],
    lightProfile: "shade",
    irrigationLine: "IR-3",
    status: "blocked",
    blockedReason: "滴灌管路维修中",
  },
];

const reservations: BenchReservation[] = [
  {
    id: "rsv-sol-east1",
    code: "RSV-0001",
    requestKey: "sample-rsv-sol-east1",
    trialId: "trial-sol-01",
    benchId: "bench-east-1",
    startDate: "2026-02-16",
    endDate: "2026-05-18",
    slots: 2,
    note: "番茄早期坐果阶段预留两个槽位。",
    status: "active",
    consumedAccessionIds: [],
    bookedOn: "2026-01-20T08:00:00.000Z",
    benchCode: "E-1",
    sectorSnapshot: "东翼",
    lightProfileSnapshot: "full-sun",
    benchStatusSnapshot: "assigned",
  },
  {
    id: "rsv-ama-west2",
    code: "RSV-0002",
    requestKey: "sample-rsv-ama-west2",
    trialId: "trial-ama-02",
    benchId: "bench-west-2",
    startDate: "2026-04-01",
    endDate: "2026-07-12",
    slots: 2,
    note: "甜菜第二批材料的周转槽位，其中一个已被 Chioggia 履约。",
    status: "active",
    consumedAccessionIds: ["acc-bee-03"],
    bookedOn: "2026-03-10T08:00:00.000Z",
    benchCode: "W-2",
    sectorSnapshot: "西翼",
    lightProfileSnapshot: "partial-shade",
    benchStatusSnapshot: "assigned",
  },
  {
    id: "rsv-sol-north1",
    code: "RSV-0003",
    requestKey: "sample-rsv-sol-north1",
    trialId: "trial-sol-01",
    benchId: "bench-north-1",
    startDate: "2026-05-01",
    endDate: "2026-08-31",
    note: "跨越试验结束日期的遮阴过渡留位。",
    slots: 2,
    status: "active",
    consumedAccessionIds: [],
    bookedOn: "2026-01-21T08:00:00.000Z",
    benchCode: "N-1",
    sectorSnapshot: "北翼",
    lightProfileSnapshot: "shade",
    benchStatusSnapshot: "available",
  },
  {
    id: "rsv-ama-west1",
    code: "RSV-0004",
    requestKey: "sample-rsv-ama-west1",
    trialId: "trial-ama-02",
    benchId: "bench-west-1",
    startDate: "2026-04-01",
    endDate: "2026-07-12",
    slots: 3,
    note: "甜菜主批次三个槽位。",
    status: "active",
    consumedAccessionIds: [],
    bookedOn: "2026-03-11T08:00:00.000Z",
    benchCode: "W-1",
    sectorSnapshot: "西翼",
    lightProfileSnapshot: "partial-shade",
    benchStatusSnapshot: "assigned",
  },
  {
    id: "rsv-bra-north2",
    code: "RSV-0005",
    requestKey: "sample-rsv-bra-north2",
    trialId: "trial-bra-03",
    benchId: "bench-north-2",
    startDate: "2026-07-20",
    endDate: "2026-10-08",
    slots: 2,
    note: "计划在滴灌维修结束后启用；维修未完成前保持失效。",
    status: "active",
    consumedAccessionIds: [],
    bookedOn: "2026-06-01T08:00:00.000Z",
    benchCode: "N-2",
    sectorSnapshot: "北翼",
    lightProfileSnapshot: "shade",
    benchStatusSnapshot: "blocked",
  },
  {
    id: "rsv-bra-west1",
    code: "RSV-0006",
    requestKey: "sample-rsv-bra-west1",
    trialId: "trial-bra-03",
    benchId: "bench-west-1",
    startDate: "2026-05-15",
    endDate: "2026-06-30",
    slots: 3,
    note: "羽衣甘蓝提前进场，与甜菜主批次竞争同一台架。",
    status: "active",
    consumedAccessionIds: [],
    bookedOn: "2026-06-02T08:00:00.000Z",
    benchCode: "W-1",
    sectorSnapshot: "西翼",
    lightProfileSnapshot: "partial-shade",
    benchStatusSnapshot: "assigned",
  },
];

const observationPasses: ObservationPass[] = [
  {
    id: "obs-tom-01",
    trialId: "trial-sol-01",
    observedOn: "2026-02-26",
    observer: "M. Ikeda",
    entries: [
      {
        accessionId: "acc-tom-01",
        heightMm: 58,
        leafCount: 6,
        ecMs: 1.8,
        notes: "穴盘内发芽整体均匀。",
      },
      {
        accessionId: "acc-tom-02",
        heightMm: 64,
        leafCount: 7,
        ecMs: 1.7,
        notes: "穴孔中根系萌发良好。",
      },
      {
        accessionId: "acc-tom-03",
        heightMm: 84,
        leafCount: 9,
        ecMs: 1.9,
        notes: "长势旺盛，但节间伸长不够均匀。",
      },
    ],
  },
  {
    id: "obs-bee-01",
    trialId: "trial-ama-02",
    observedOn: "2026-04-08",
    observer: "R. Ono",
    entries: [
      {
        accessionId: "acc-bee-01",
        heightMm: 62,
        leafCount: 8,
        ecMs: 2.1,
        notes: "第一片真叶出现红色色素。",
      },
      {
        accessionId: "acc-bee-02",
        heightMm: 68,
        leafCount: 8,
        ecMs: 2.0,
        notes: "金色叶片色调发展均匀。",
      },
      {
        accessionId: "acc-bee-03",
        heightMm: 54,
        leafCount: 6,
        ecMs: 2.2,
        notes: "穴盘边缘有轻微倒苗。",
      },
    ],
  },
];

const flags: Flag[] = [
  {
    id: "flag-tom-01",
    trialId: "trial-sol-01",
    accessionId: "acc-tom-01",
    observationPassId: "obs-tom-01",
    code: "HT_UNDER",
    message: "Tiny Tim 低于 60 毫米生长阈值",
    severity: "warning",
    state: "open",
    createdOn: "2026-02-26T09:00:00.000Z",
  },
  {
    id: "flag-bee-01",
    trialId: "trial-ama-02",
    accessionId: "acc-bee-03",
    observationPassId: "obs-bee-01",
    code: "HT_UNDER",
    message: "Chioggia 低于 60 毫米生长阈值",
    severity: "warning",
    state: "open",
    createdOn: "2026-04-08T09:00:00.000Z",
  },
];

const clearanceSnapshots: ClearanceSnapshot[] = [];

export function createSampleWorkspaceState(): WorkspaceState {
  return {
    trials,
    accessions,
    benches,
    reservations,
    observationPasses,
    flags,
    clearanceSnapshots,
  };
}
