import type {
  Accession,
  Bench,
  ClearanceSnapshot,
  DedupAudit,
  DuplicateReview,
  Flag,
  ObservationPass,
  Trial,
  WorkspaceState,
} from "../domain/types";
import { fingerprintObservationPass } from "../domain/dedup";

const trials: Trial[] = [
  {
    id: "trial-sol-01",
    code: "SOL-01",
    cropFamily: "茄科",
    objective: "比较紧凑型番茄品种在温室内的早期坐果表现。",
    season: "春季",
    startDate: "2026-02-16",
    endDate: "2026-05-18",
    state: "active",
  },
  {
    id: "trial-ama-02",
    code: "AMA-02",
    cropFamily: "苋科",
    objective: "在限水条件下评估三个甜菜批次的叶片品质。",
    season: "夏季",
    startDate: "2026-04-01",
    endDate: "2026-07-12",
    state: "active",
  },
  {
    id: "trial-bra-03",
    code: "BRA-03",
    cropFamily: "十字花科",
    objective: "筛选羽衣甘蓝品系的早期茎秆强度和叶片一致性。",
    season: "秋季",
    startDate: "2026-07-20",
    endDate: "2026-10-08",
    state: "draft",
  },
];

const accessions: Accession[] = [
  {
    id: "acc-tom-01",
    trialId: "trial-sol-01",
    accessionNo: "ACC-0001",
    cultivar: "Tiny Tim",
    source: "Pioneer Seed Lab",
    propagatedOn: "2026-02-18",
    quantity: 96,
    trayCells: 104,
    preferredLight: "full-sun",
    genotypeNote: "有限生长型矮化品系，节间紧凑。",
    labels: ["矮化", "早熟"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-tom-02",
    trialId: "trial-sol-01",
    accessionNo: "ACC-0002",
    cultivar: "Micro Tom",
    source: "Pioneer Seed Lab",
    propagatedOn: "2026-02-18",
    quantity: 96,
    trayCells: 104,
    preferredLight: "full-sun",
    genotypeNote: "矮化品种，单盆果实密度较高。",
    labels: ["矮化", "果实"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-tom-03",
    trialId: "trial-sol-01",
    accessionNo: "ACC-0003",
    cultivar: "Yellow Pear",
    source: "Regional Germplasm Bank",
    propagatedOn: "2026-02-20",
    quantity: 72,
    trayCells: 128,
    preferredLight: "full-sun",
    genotypeNote: "无限生长型樱桃番茄品系，用于活力比较。",
    labels: ["樱桃", "活力"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-bee-01",
    trialId: "trial-ama-02",
    accessionNo: "ACC-0004",
    cultivar: "Bull's Blood",
    source: "Root Heritage",
    propagatedOn: "2026-04-01",
    quantity: 120,
    trayCells: 128,
    preferredLight: "partial-shade",
    genotypeNote: "深红叶用批次，中等耐热性。",
    labels: ["叶用", "颜色"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-bee-02",
    trialId: "trial-ama-02",
    accessionNo: "ACC-0005",
    cultivar: "Golden Detroit",
    source: "Root Heritage",
    propagatedOn: "2026-04-01",
    quantity: 120,
    trayCells: 128,
    preferredLight: "partial-shade",
    genotypeNote: "金色甜菜品系，用于低草酸筛选。",
    labels: ["金色", "低草酸"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-bee-03",
    trialId: "trial-ama-02",
    accessionNo: "ACC-0006",
    cultivar: "Chioggia",
    source: "Root Heritage",
    propagatedOn: "2026-04-02",
    quantity: 90,
    trayCells: 72,
    preferredLight: "partial-shade",
    genotypeNote: "条纹甜菜，用于质地和储藏性检查。",
    labels: ["条纹", "储藏"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-kale-01",
    trialId: "trial-bra-03",
    accessionNo: "ACC-0007",
    cultivar: "Lacinato",
    source: "Brassica Works",
    propagatedOn: "2026-07-20",
    quantity: 80,
    trayCells: 72,
    preferredLight: "partial-shade",
    genotypeNote: "传统羽衣甘蓝品系，叶片深色且有褶皱。",
    labels: ["传统", "叶用"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
  {
    id: "acc-kale-02",
    trialId: "trial-bra-03",
    accessionNo: "ACC-0008",
    cultivar: "Winterbor",
    source: "Brassica Works",
    propagatedOn: "2026-07-20",
    quantity: 80,
    trayCells: 72,
    preferredLight: "partial-shade",
    genotypeNote: "卷叶羽衣甘蓝杂交种，耐寒性较好。",
    labels: ["杂交", "耐寒"],
    lifecycleStatus: "active",
    retirementHistory: [],
  },
];

const benches: Bench[] = [
  {
    id: "bench-east-1",
    code: "E-1",
    sector: "东翼",
    capacity: 4,
    assignedIds: ["acc-tom-01", "acc-tom-02"],
    lightProfile: "full-sun",
    irrigationLine: "IR-1",
    status: "assigned",
  },
  {
    id: "bench-east-2",
    code: "E-2",
    sector: "东翼",
    capacity: 4,
    assignedIds: [],
    lightProfile: "full-sun",
    irrigationLine: "IR-1",
    status: "available",
  },
  {
    id: "bench-west-1",
    code: "W-1",
    sector: "西翼",
    capacity: 5,
    assignedIds: ["acc-bee-01", "acc-bee-02"],
    lightProfile: "partial-shade",
    irrigationLine: "IR-2",
    status: "assigned",
  },
  {
    id: "bench-west-2",
    code: "W-2",
    sector: "西翼",
    capacity: 5,
    assignedIds: ["acc-bee-03"],
    lightProfile: "partial-shade",
    irrigationLine: "IR-2",
    status: "assigned",
  },
  {
    id: "bench-north-1",
    code: "N-1",
    sector: "北翼",
    capacity: 4,
    assignedIds: [],
    lightProfile: "shade",
    irrigationLine: "IR-3",
    status: "available",
  },
  {
    id: "bench-north-2",
    code: "N-2",
    sector: "北翼",
    capacity: 4,
    assignedIds: [],
    lightProfile: "shade",
    irrigationLine: "IR-3",
    status: "blocked",
    blockedReason: "滴灌管路维修中",
  },
];

/** 为示例观测补齐身份三元组（示例数据视为去重机制上线时迁移的历史观测）。 */
function samplePass(pass: Omit<ObservationPass, "idempotencyToken" | "contentFingerprint" | "recordedAt" | "dedupStatus" | "convergedAccessionIds"> &
  Partial<Pick<ObservationPass, "dedupStatus" | "convergedAccessionIds" | "recordedAt" | "canonicalPassId">>): ObservationPass {
  const built: ObservationPass = {
    ...pass,
    idempotencyToken: `legacy_idem_${pass.id}`,
    contentFingerprint: "",
    recordedAt: pass.recordedAt ?? `${pass.observedOn}T08:00:00.000Z`,
    dedupStatus: pass.dedupStatus ?? "canonical",
    convergedAccessionIds: pass.convergedAccessionIds ?? [],
  };
  return { ...built, contentFingerprint: fingerprintObservationPass(built) };
}

const observationPasses: ObservationPass[] = [
  samplePass({
    id: "obs-tom-01",
    trialId: "trial-sol-01",
    observedOn: "2026-02-26",
    observer: "M. Ikeda",
    entries: [
      {
        accessionId: "acc-tom-01",
        heightMm: 58,
        leafCount: 6,
        ecMs: 1.8,
        notes: "穴盘内发芽整体均匀。",
      },
      {
        accessionId: "acc-tom-02",
        heightMm: 64,
        leafCount: 7,
        ecMs: 1.7,
        notes: "穴孔中根系萌发良好。",
      },
      {
        accessionId: "acc-tom-03",
        heightMm: 84,
        leafCount: 9,
        ecMs: 1.9,
        notes: "长势旺盛，但节间伸长不够均匀。",
      },
    ],
  }),
  samplePass({
    id: "obs-bee-01",
    trialId: "trial-ama-02",
    observedOn: "2026-04-08",
    observer: "R. Ono",
    entries: [
      {
        accessionId: "acc-bee-01",
        heightMm: 62,
        leafCount: 8,
        ecMs: 2.1,
        notes: "第一片真叶出现红色色素。",
      },
      {
        accessionId: "acc-bee-02",
        heightMm: 68,
        leafCount: 8,
        ecMs: 2.0,
        notes: "金色叶片色调发展均匀。",
      },
      {
        accessionId: "acc-bee-03",
        heightMm: 54,
        leafCount: 6,
        ecMs: 2.2,
        notes: "穴盘边缘有轻微倒苗。",
      },
    ],
  }),
  // 场景 A：字节级重复录入（内容指纹一致），系统已自动收敛到 obs-bee-02a。
  samplePass({
    id: "obs-bee-02a",
    trialId: "trial-ama-02",
    observedOn: "2026-04-15",
    observer: "R. Ono",
    recordedAt: "2026-04-15T08:30:00.000Z",
    entries: [
      { accessionId: "acc-bee-01", heightMm: 70, leafCount: 9, ecMs: 2.0, notes: "" },
      { accessionId: "acc-bee-02", heightMm: 74, leafCount: 9, ecMs: 1.9, notes: "" },
    ],
  }),
  samplePass({
    id: "obs-bee-02b-dup",
    trialId: "trial-ama-02",
    observedOn: "2026-04-15",
    observer: "R. Ono",
    recordedAt: "2026-04-15T08:31:10.000Z",
    dedupStatus: "converged",
    canonicalPassId: "obs-bee-02a",
    convergedAccessionIds: ["acc-bee-01", "acc-bee-02"],
    entries: [
      { accessionId: "acc-bee-01", heightMm: 70, leafCount: 9, ecMs: 2.0, notes: "" },
      { accessionId: "acc-bee-02", heightMm: 74, leafCount: 9, ecMs: 1.9, notes: "" },
    ],
  }),
  // 场景 B：容差内重测，等待人工裁决（54 vs 57mm，超出 5mm？|57-54|=3，容差内）。
  samplePass({
    id: "obs-bee-03",
    trialId: "trial-ama-02",
    observedOn: "2026-04-22",
    observer: "R. Ono",
    recordedAt: "2026-04-22T08:00:00.000Z",
    entries: [
      { accessionId: "acc-bee-03", heightMm: 54, leafCount: 7, ecMs: 2.1, notes: "" },
    ],
  }),
  samplePass({
    id: "obs-bee-04",
    trialId: "trial-ama-02",
    observedOn: "2026-04-22",
    observer: "R. Ono",
    recordedAt: "2026-04-22T15:20:00.000Z",
    entries: [
      { accessionId: "acc-bee-03", heightMm: 57, leafCount: 7, ecMs: 2.2, notes: "下午复测，读数略高" },
    ],
  }),
  // 场景 C：显著差异的同日重测，人工已裁决两条都保留（合理重测）。
  samplePass({
    id: "obs-bee-05",
    trialId: "trial-ama-02",
    observedOn: "2026-05-06",
    observer: "R. Ono",
    recordedAt: "2026-05-06T08:00:00.000Z",
    entries: [
      { accessionId: "acc-bee-01", heightMm: 78, leafCount: 10, ecMs: 2.0, notes: "" },
    ],
  }),
  samplePass({
    id: "obs-bee-06",
    trialId: "trial-ama-02",
    observedOn: "2026-05-06",
    observer: "R. Ono",
    recordedAt: "2026-05-06T17:30:00.000Z",
    entries: [
      { accessionId: "acc-bee-01", heightMm: 96, leafCount: 12, ecMs: 2.6, notes: "傍晚复测，植株明显伸长" },
    ],
  }),
];

const duplicateReviews: DuplicateReview[] = [
  {
    id: "rev-bee-pending-01",
    trialId: "trial-ama-02",
    status: "pending",
    candidatePassId: "obs-bee-04",
    existingPassId: "obs-bee-03",
    sharedAccessionIds: ["acc-bee-03"],
    differences: [
      {
        accessionId: "acc-bee-03",
        heightDeltaMm: 3,
        leafDelta: 0,
        ecDelta: 0.1,
        withinTolerance: true,
      },
    ],
    suggestion: "converge",
    createdAt: "2026-04-22T15:20:00.000Z",
  },
  {
    id: "rev-bee-resolved-01",
    trialId: "trial-ama-02",
    status: "resolved",
    candidatePassId: "obs-bee-06",
    existingPassId: "obs-bee-05",
    sharedAccessionIds: ["acc-bee-01"],
    differences: [
      {
        accessionId: "acc-bee-01",
        heightDeltaMm: 18,
        leafDelta: 2,
        ecDelta: 0.6,
        withinTolerance: false,
      },
    ],
    suggestion: "keep_both",
    createdAt: "2026-05-06T17:30:00.000Z",
    decidedAt: "2026-05-07T01:00:00.000Z",
    decidedBy: "L. Tanaka",
    verdict: "keep_both",
    decisionNote: "两次测量间隔近 10 小时且株高差异 18 mm，属于植株真实生长，按合理重测保留两条。",
  },
];

const dedupAudits: DedupAudit[] = [
  {
    id: "aud-bee-auto-01",
    trialId: "trial-ama-02",
    at: "2026-04-15T08:31:10.000Z",
    kind: "auto_converged",
    candidatePassId: "obs-bee-02b-dup",
    canonicalPassId: "obs-bee-02a",
    convergedAccessionIds: ["acc-bee-01", "acc-bee-02"],
    reason: "内容指纹完全一致且在自动收敛窗口内，判定为重复录入",
    matchedBy: "fingerprint",
  },
  {
    id: "aud-bee-manual-01",
    trialId: "trial-ama-02",
    at: "2026-05-07T01:00:00.000Z",
    kind: "manual",
    candidatePassId: "obs-bee-06",
    canonicalPassId: "obs-bee-05",
    convergedAccessionIds: [],
    reason: "人工裁决保留两次观测（合理重测）",
    matchedBy: "manual_review",
    reviewId: "rev-bee-resolved-01",
    decidedBy: "L. Tanaka",
    decisionNote: "两次测量间隔近 10 小时且株高差异 18 mm，属于植株真实生长，按合理重测保留两条。",
    verdict: "keep_both",
  },
];

const flags: Flag[] = [
  {
    id: "flag-tom-01",
    trialId: "trial-sol-01",
    accessionId: "acc-tom-01",
    observationPassId: "obs-tom-01",
    code: "HT_UNDER",
    message: "Tiny Tim 低于 60 毫米生长阈值",
    severity: "warning",
    state: "open",
    createdOn: "2026-02-26T09:00:00.000Z",
  },
  {
    id: "flag-bee-01",
    trialId: "trial-ama-02",
    accessionId: "acc-bee-03",
    observationPassId: "obs-bee-01",
    code: "HT_UNDER",
    message: "Chioggia 低于 60 毫米生长阈值",
    severity: "warning",
    state: "open",
    createdOn: "2026-04-08T09:00:00.000Z",
  },
];

const clearanceSnapshots: ClearanceSnapshot[] = [];

export function createSampleWorkspaceState(): WorkspaceState {
  return {
    trials,
    accessions,
    benches,
    observationPasses,
    flags,
    clearanceSnapshots,
    duplicateReviews,
    dedupAudits,
  };
}
